<a href="https://colab.research.google.com/github/djnickeysm/Magic-Pioneer-2023/blob/main/notebooks/COOP_SQL_Murder_Mystery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL Murder Mystery!
Adapted By: Martin Arroyo

![Detective making connections between points](https://github.com/freestackinitiative/coop_sql_notebooks/blob/v2/assets/sleuth.png?raw=1)

**Credit**

This material was adapted from the [SQL Murder Mystery by Knight Lab](https://mystery.knightlab.com/) under [Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). The SQL Murder Mystery was originally created by [Joon Park](https://twitter.com/joonparkmusic) and [Cathy He](https://twitter.com/Cathy_MeiyingHe) while they were Knight Lab fellows. See the [GitHub repository](https://github.com/NUKnightLab/sql-mysteries) for more information.

## Scenario

A crime has taken place and detectives need your help! You were given the crime scene report, but you somehow lost it. You vaguely remember that the crime was a `​murder`​ that occurred sometime on `​January 15, 2018`​ and that it took place in ​`SQL City`​. It is up to you to find out who the murderer is using just your SQL skills and resourcefulness. You are given a connection to the Police Department's database which has all of the clues you'll need to track down the killer.

Use the skills you developed in SQL 101 and 102, along with any resources you like, to solve the `SQL Murder Mystery`!

## Connect to the Police Department Database

To get started and run your queries, press play in the cell below to connect to the Police Department database.

To run queries, create a new `Code` cell and write `%%sql` at the top of it. Then you can write your queries underneath. See the example below:
```python
%%sql

SELECT *
FROM table

```

In [1]:
%%capture --no-stderr
# @title Press Play { display-mode: "form" }
# Install `teachdb` and `coop_grader`
print("Installing `teachdb` and its dependencies...")
%pip install --quiet --upgrade git+https://github.com/freestackinitiative/teachingdb.git git+https://github.com/martinmarroyo/coop_grader.git
print("Successfully installed `teachdb`")
from teachdb.teachdb import connect_teachdb
from coop_grader.sql_murder_mystery.check_suspect import check_suspect
# Set configurations for notebook & load data
con = connect_teachdb(database="sql_murder_mystery")

%sql con

## Discovering tables in the database

We start our quest to find the murderer by exploring the Police Department database. But you haven't seen the database yet, and you don't know what the tables are, so how do you know what to look for?

Thankfully, most relational database management systems have this information stored in a place where you can query it. Very often, a special schema known as the [`information_schema`](https://en.wikipedia.org/wiki/Information_schema) is used to store information about the tables and columns in your database (aka metadata.) The police department's database has an information schema, with the `tables` view showing you what tables are available, and the `columns` view which shows you all the columns for each table and their data types.

### Listing all the tables in the Police Database

#### Check the [`information_schema.tables` description](https://duckdb.org/docs/sql/information_schema.html#tables-and-views)

First, we'll look at all the tables available to us by checking the `information_schema.tables` view. We'll give you the first query to start, but from here on out you will have to come up with the remaining queries using your SQL knowledge and your resourcefulness.

Here is the query that is needed to show you the tables in the Police Department Database. Copy/Paste it into the cell below and run it to see the tables available to you:

>```sql
>SELECT *
>FROM information_schema.tables
>```

In [2]:
%%sql

SELECT *
FROM information_schema.tables

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action,TABLE_COMMENT
0,memory,main,crime_scene_report,BASE TABLE,None,None,None,None,None,YES,NO,None,None
1,memory,main,drivers_license,BASE TABLE,None,None,None,None,None,YES,NO,None,None
2,memory,main,facebook_event_checkin,BASE TABLE,None,None,None,None,None,YES,NO,None,None
3,memory,main,get_fit_now_check_in,BASE TABLE,None,None,None,None,None,YES,NO,None,None
4,memory,main,get_fit_now_member,BASE TABLE,None,None,None,None,None,YES,NO,None,None
5,memory,main,income,BASE TABLE,None,None,None,None,None,YES,NO,None,None
6,memory,main,interview,BASE TABLE,None,None,None,None,None,YES,NO,None,None
7,memory,main,person,BASE TABLE,None,None,None,None,None,YES,NO,None,None

### Listing all the tables and their columns in the Police Database

**Check the [`information_schema.columns` description](https://duckdb.org/docs/sql/information_schema.html#columns)**

Great! Now that you know what tables are available, it's time to find out the columns that each table has along with the data type of each column. Write a query that shows the table name, column name, and data type for each table in the Police Department database using the `information_schema.columns` view. Make sure that the output is ordered by table, then column name (ascending):

*Optional hints - try to only use them if you get **REALLY** stuck!*

<details>
<summary>Hint 1</summary>
<p>Structure your query just like we did in the previous one where we looked at `information_schema.tables`</p>
</details>

<details>
<summary>Hint 2</summary>
<p>Make sure to check the link for the information_schema.columns description! It will tell you the column names that you should use for the query. Remember, we want the table name, column name, and data type - check the description to find the appropriate names!</p>
</details>

<details>
<summary>Hint 3</summary>
<p>Don't forget to use the ORDER BY statement to order your search results. We are looking to sort both columns in ascending order, which can be specified using the ASC keyword, however, it is also the default sort order, so ASC is not necessarily required.</p>
</details>

In [4]:
%%sql

SELECT table_name, column_name, data_type
FROM information_schema.columns
ORDER BY table_name, column_name ASC

                table_name            column_name data_type
0       crime_scene_report                   city   VARCHAR
1       crime_scene_report                   date   INTEGER
2       crime_scene_report            description   VARCHAR
3       crime_scene_report                   type   VARCHAR
4          drivers_license                    age   INTEGER
5          drivers_license               car_make   VARCHAR
6          drivers_license              car_model   VARCHAR
7          drivers_license              eye_color   VARCHAR
8          drivers_license                 gender   VARCHAR
9          drivers_license             hair_color   VARCHAR
10         drivers_license                 height   INTEGER
11         drivers_license                     id   INTEGER
12         drivers_license           plate_number   VARCHAR
13  facebook_event_checkin                   date   INTEGER
14  facebook_event_checkin               event_id   INTEGER
15  facebook_event_checkin             event_name   VARCHAR
16  facebook_event_checkin              person_id   INTEGER
17    get_fit_now_check_in          check_in_date   INTEGER
18    get_fit_now_check_in          check_in_time   INTEGER
19    get_fit_now_check_in         check_out_time   INTEGER
20    get_fit_now_check_in          membership_id   VARCHAR
21      get_fit_now_member                     id   VARCHAR
22      get_fit_now_member  membership_start_date   INTEGER
23      get_fit_now_member      membership_status   VARCHAR
24      get_fit_now_member                   name   VARCHAR
25      get_fit_now_member              person_id   INTEGER
26                  income          annual_income   INTEGER
27                  income                    ssn   INTEGER
28               interview              person_id   INTEGER
29               interview             transcript   VARCHAR
30                  person         address_number   INTEGER
31                  person    address_street_name   VARCHAR
32                  person                     id   INTEGER
33                  person             license_id   INTEGER
34                  person                   name   VARCHAR
35                  person                    ssn   INTEGER

### Entity Relationship Diagram (Optional)

After doing some detective work and finding the tables in the Police Department database, you discover that there is an ERD! This can be really helpful in your quest to find the murderer. If you like, challenge yourself (and your SQL skills) to continue on by just querying the `information_schema` as needed. Otherwise, you can click the dropdown below to reveal the ERD to help you see the tables and relationships in the Police Department database at a glance:

<details>
  <summary>Check the SQL Murder Mystery ERD</summary>
  <img src="https://github.com/freestackinitiative/coop_sql_notebooks/blob/v2/assets/murder_mystery_schema.png?raw=1" alt="ERD for SQL Murder Mystery"/>
</details>

## Beginning your investigation

Start by retrieving the corresponding crime scene report from the police department’s database.

<details>
<summary>Clue #1</summary>
<p>Look at the tables available in the Police Department database. Could the crime scene report be in there?</p>
</details>

<details>
<summary>Clue #2</summary>
<p>The murder occured on January 15, 2018 in SQL City. Perhaps filtering your query with this information can help you find that crime report you're looking for...</p>
</details>

In [32]:
%%sql

SELECT *
FROM crime_scene_report
WHERE date = '20180115' AND city = 'SQL City' AND type = 'murder'

,date,type,description,city
0,20180115,murder,Security footage shows that there were 2 witnesses. The first witness lives at the last house o...,SQL City

___

## Solving the Mystery (and checking if you cracked the case!)

From here on out, you'll be using your skills and the clues in the Police Department database to find the killer. When you think you have found the killer, come back to this section and use the cell below to check your answer and see if you found the murderer:

ex:
```python
check_suspect("Adam Levine")
```

In [89]:
check_suspect("Miranda Priestly")

Congrats, you found the brains behind the murder!
Everyone in SQL City hails you as the greatest SQL detective of all time.
Time to break out the champagne!

True

In [58]:
check_suspect("Jeremy Bowers")

Congrats, you found the murderer! But wait, there's more... If you think you're up for a challenge,try querying the interview transcript of the murderer to find the real villain behind this crime.If you feel especially confident in your SQL skills, try to complete this final step with no more than 2 queries.
Use this same `check_suspect` function with your new suspect to check your answer.

True

---

## Workspace

Use the cells below to write your queries and work on solving the mystery. When you have a suspect, check your answer using the [cell above this one](#solving-the-mystery-and-checking-if-you-cracked-the-case) and running their name through the `check_suspect` function. If you find the murderer, the function will tell you.

Don't forget to use `%%sql` at the top of the `Code` cells you create in order to get your SQL queries to work. Good luck, sleuths!

In [88]:
%%sql

SELECT *
FROM facebook_event_checkin
WHERE event_name LIKE 'SQL%' AND date >='20171200' AND date <= '20171231'
ORDER BY date ASC

-- I unfortunately failed to do COUNT(DISTINCT person_id), but I am suspecting Miranda Priestly (person_id = '99716')

    person_id  event_id            event_name      date
0       81526      1143  SQL Symphony Concert  20171202
1       79312      1143  SQL Symphony Concert  20171203
2       69325      1143  SQL Symphony Concert  20171206
3       99716      1143  SQL Symphony Concert  20171206
4       67318      1143  SQL Symphony Concert  20171206
5       43366      1143  SQL Symphony Concert  20171207
6       24556      1143  SQL Symphony Concert  20171207
7       24397      1143  SQL Symphony Concert  20171208
8       92343      1143  SQL Symphony Concert  20171212
9       99716      1143  SQL Symphony Concert  20171212
10      19292      1143  SQL Symphony Concert  20171213
11      19260      1143  SQL Symphony Concert  20171214
12      69699      1143  SQL Symphony Concert  20171214
13      28582      1143  SQL Symphony Concert  20171215
14      58898      1143  SQL Symphony Concert  20171220
15      28582      1143  SQL Symphony Concert  20171220
16      24556      1143  SQL Symphony Concert  20171221
17      11173      1143  SQL Symphony Concert  20171223
18      24556      1143  SQL Symphony Concert  20171224
19      62596      1143  SQL Symphony Concert  20171225
20      99716      1143  SQL Symphony Concert  20171229

In [68]:
%%sql

SELECT *
FROM person
WHERE license_id = '202298' OR license_id = '291182' OR license_id = '918773'

--Let's check the SQL Symphony Concert

,id,name,license_id,address_number,address_street_name,ssn
0,78881,Red Korb,918773,107,Camerata Dr,961388910
1,99716,Miranda Priestly,202298,1883,Golden Ave,987756388
2,90700,Regina George,291182,332,Maple Ave,337169072

In [66]:
%%sql

SELECT *
FROM drivers_license
WHERE car_make = 'Tesla' AND car_model = 'Model S' AND hair_color = 'red' AND gender = 'female'

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,202298,68,66,green,red,female,500123,Tesla,Model S
1,291182,65,66,blue,red,female,08CM64,Tesla,Model S
2,918773,48,65,black,red,female,917UU3,Tesla,Model S

In [62]:
%%sql

SELECT *
FROM interview
WHERE person_id = '67318'
LIMIT 10

--According to transcript, Jeremy was hired by a woman with a height (5'5" / 65" OR 5'7" / 67"), hair is red, drives a
--Tesla Model S
--Attended SQL Symphony Concert 3 times in December 2017

,person_id,transcript
0,67318,"I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5"" ..."

In [57]:
%%sql

SELECT *
FROM drivers_license
WHERE id = '173289'

--There is no information on Joe Germuska
--UPDATE: The murderer is Jeremy Bowers!

Empty DataFrame
Columns: [id, age, height, eye_color, hair_color, gender, plate_number, car_make, car_model]
Index: []

In [56]:
%%sql

SELECT *
FROM drivers_license
WHERE id = '423327'

--I'm suspecting Jeremy Bowers

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,423327,30,70,brown,brown,male,0H42W2,Chevrolet,Spark LS

In [53]:
%%sql

SELECT *
FROM person
WHERE id = '67318'

,id,name,license_id,address_number,address_street_name,ssn
0,67318,Jeremy Bowers,423327,530,"Washington Pl, Apt 3A",871539279

In [52]:
%%sql

SELECT *
FROM person
WHERE id = '28819'

,id,name,license_id,address_number,address_street_name,ssn
0,28819,Joe Germuska,173289,111,Fisk Rd,138909730

In [50]:
%%sql

SELECT *
FROM get_fit_now_member
WHERE id LIKE '48Z%' AND membership_status = 'gold'

--48Z7A(id), 28819(person_id) - Joe Germuska
--48Z55(id), 67318(person_id) - Jeremy Bowers

      id  person_id           name  membership_start_date membership_status
0  48Z7A      28819   Joe Germuska               20160305              gold
1  48Z55      67318  Jeremy Bowers               20160101              gold

In [47]:
%%sql

SELECT *
FROM get_fit_now_check_in
WHERE check_in_date = '20180109' AND membership_id LIKE '48Z%'

  membership_id  check_in_date  check_in_time  check_out_time
0         48Z7A       20180109           1600            1730
1         48Z55       20180109           1530            1700

In [37]:
%%sql

SELECT transcript
FROM interview
WHERE person_id = '14887'

--According to Morty, the killer has "Get Fit Now Gym" bag, membership starts with "48Z", is gold member, car plate has "H42W"

                                                                                           transcript
0  I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership nu...

In [35]:
%%sql

SELECT transcript
FROM interview
WHERE person_id = '16371'

--Annabel recognized the killer from the gym while working out on January 09.

                                                                                           transcript
0  I saw the murder happen, and I recognized the killer from my gym when I was working out last we...

In [28]:
%%sql

SELECT *
FROM person
WHERE address_street_name = 'Franklin Ave' AND name = 'Annabel Miller'

--So far, only Annabel Miller

,id,name,license_id,address_number,address_street_name,ssn
0,16371,Annabel Miller,490173,103,Franklin Ave,318771143

In [91]:
%%sql

SELECT *
FROM person
WHERE address_street_name = 'Northwestern Dr'
ORDER BY address_number DESC
LIMIT 10

--I am suspecting Morty Schapiro (id = '14887')

,id,name,license_id,address_number,address_street_name,ssn
0,14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949
1,17729,Lasonya Wildey,439686,3824,Northwestern Dr,917817122
2,53890,Sophie Tiberio,957671,3755,Northwestern Dr,442830147
3,73368,Torie Thalmann,773862,3697,Northwestern Dr,341559436
4,96595,Coretta Cubie,303645,3631,Northwestern Dr,378403829
5,19420,Cody Schiel,890431,3524,Northwestern Dr,947110049
6,93509,Emmitt Aceuedo,916706,3491,Northwestern Dr,979073160
7,87456,Leonora Wolfsberger,215868,3483,Northwestern Dr,565203106
8,36378,Freddie Ellzey,267882,3449,Northwestern Dr,474117596
9,53076,Boris Bijou,664914,3327,Northwestern Dr,401191868